export const ActionTypes = {
  FETCH_NEWS: 'FETCH_NEWS',
  FETCH_NEWS_SUCCESS: 'FETCH_NEWS_SUCCESS',
  FETCH_NEWS_FAIL: 'FETCH_NEWS_FAIL',

  FETCH_MORE_NEWS: 'FETCH_MORE_NEWS',
  FETCH_MORE_NEWS_SUCCESS: 'FETCH_MORE_NEWS_SUCCESS',
  FETCH_MORE_NEWS_FAIL: 'FETCH_MORE_NEWS_FAIL',

  FETCH_SOURCES_SUCCESS: 'FETCH_SOURCES_SUCCESS',

  FETCH_NEWS_BY_SOURCE: 'FETCH_NEWS_BY_SOURCE',
  FETCH_NEWS_BY_SOURCE_SUCCESS: 'FETCH_NEWS_BY_SOURCE_SUCCESS',
  FETCH_NEWS_BY_SOURCE_FAIL: 'FETCH_NEWS_BY_SOURCE_FAIL'
}
